#!/usr/bin/env bash
# Common utility functions for dotfiles installation

set -euo pipefail

# Colors (matching install.sh)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1" >&2
}

log_step() {
    echo ""
    echo -e "${CYAN}→ $1${NC}"
}

# Check if command exists
command_exists() {
    command -v "$1" &> /dev/null
}

# Check if package is installed (Linux)
package_installed() {
    local package="$1"
    local os=$(detect_os)

    case "$os" in
        macos)
            brew list "$1" &> /dev/null
            ;;
        fedora|oracle|rocky)
            rpm -q "$1" &> /dev/null
            ;;
        ubuntu|rpi)
            dpkg -l "$1" 2>/dev/null | grep -q '^ii'
            ;;
        arch)
            pacman -Qi "$1" &> /dev/null
            ;;
        void)
            xbps-query "$1" &> /dev/null
            ;;
        gentoo)
            equery list "$1" &> /dev/null
            ;;
        alpine)
            apk info -e "$1" &> /dev/null
            ;;
        freebsd)
            pkg info "$1" &> /dev/null
            ;;
        windows)
            # Check Windows package managers or PATH
            command_exists "$1"
            ;;
        *)
            return 1
            ;;
    esac
}

# Install package (if not already installed)
ensure_package() {
    local package="$1"
    local os=$(detect_os)

    if package_installed "$package"; then
        log_info "$package already installed"
        return 0
    fi

    log_step "Installing $package..."

    case "$os" in
        macos)
            if command_exists brew; then
                brew install "$package"
            else
                log_error "Homebrew not found. Please install from https://brew.sh"
                return 1
            fi
            ;;
        fedora|oracle|rocky)
            sudo dnf install -y "$package"
            ;;
        ubuntu|rpi)
            sudo apt update && sudo apt install -y "$package"
            ;;
        arch)
            sudo pacman -S --noconfirm "$package"
            ;;
        void)
            sudo xbps-install -Sy "$package"
            ;;
        gentoo)
            sudo emerge --quiet "$package"
            ;;
        alpine)
            sudo apk add "$package"
            ;;
        freebsd)
            sudo pkg install -y "$package"
            ;;
        windows)
            log_warning "Please install $package manually on Windows"
            ;;
        *)
            log_error "Unsupported OS: $os"
            return 1
            ;;
    esac

    log_success "$package installed"
}

# Create symlink with backup
safe_symlink() {
    local source="$1"
    local target="$2"

    # Create target directory if it doesn't exist
    local target_dir
    target_dir=$(dirname "$target")
    mkdir -p "$target_dir"

    # Backup existing file/symlink
    if [ -e "$target" ] && [ ! -L "$target" ]; then
        local backup="${target}.backup.$(date +%Y%m%d%H%M%S)"
        log_warning "Backing up existing $target to $backup"
        mv "$target" "$backup"
    fi

    # Create symlink
    ln -sf "$source" "$target"
    log_success "Linked $target → $source"
}

# Merge configuration files
# Usage: merge_config <base_file> <os_override_file> <output_file>
merge_config() {
    local base_file="$1"
    local os_file="$2"
    local output_file="$3"

    mkdir -p "$(dirname "$output_file")"

    if [ ! -f "$base_file" ]; then
        log_error "Base config not found: $base_file"
        return 1
    fi

    # If no OS override, just copy base
    if [ ! -f "$os_file" ]; then
        cp "$base_file" "$output_file"
        log_success "Installed base config to $output_file"
        return 0
    fi

    # Determine file type and merge accordingly
    local ext="${base_file##*.}"

    case "$ext" in
        sh|bash|zsh|fish)
            # Shell scripts: source base then OS override
            {
                echo "# Auto-generated by greg-config installer"
                echo "# DO NOT EDIT directly - edit source in ~/.local/share/greg-config"
                echo ""
                echo "# Base configuration"
                echo "source '$base_file'"
                echo ""
                echo "# OS-specific overrides"
                echo "source '$os_file'"
            } > "$output_file"
            ;;
        lua)
            # Lua: load base then OS override (Neovim style)
            {
                echo "-- Auto-generated by greg-config installer"
                echo "-- DO NOT edit directly"
                echo ""
                echo "-- Load base configuration"
                echo "dofile('$base_file')"
                echo ""
                echo "-- Load OS-specific overrides"
                echo "dofile('$os_file')"
            } > "$output_file"
            ;;
        yaml|yml)
            # YAML: concatenate (assumes sections are additive)
            cat "$base_file" "$os_file" > "$output_file"
            ;;
        toml)
            # TOML: concatenate (simple merge, assumes no duplicate keys)
            cat "$base_file" "$os_file" > "$output_file"
            ;;
        *)
            # Default: concatenate
            cat "$base_file" "$os_file" > "$output_file"
            ;;
    esac

    log_success "Merged config to $output_file"
}

# Ensure directory exists
ensure_dir() {
    local dir="$1"
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
        log_success "Created directory: $dir"
    fi
}

# Confirm with user
confirm() {
    local prompt="$1"
    local response

    while true; do
        read -rp "${prompt} [y/N] " response
        case "$response" in
            [Yy]|[Yy][Ee][Ss])
                return 0
                ;;
            [Nn]|[Nn][Oo]|"")
                return 1
                ;;
            *)
                echo "Please answer yes or no"
                ;;
        esac
    done
}

# Detect shell (for shell-specific installations)
detect_shell() {
    if [ -n "${ZSH_VERSION:-}" ]; then
        echo "zsh"
    elif [ -n "${FISH_VERSION:-}" ]; then
        echo "fish"
    elif [ -n "${BASH_VERSION:-}" ]; then
        echo "bash"
    elif [ -n "${NU_VERSION:-}" ]; then
        echo "nushell"
    else
        echo "unknown"
    fi
}

# Get config directory (XDG compliant)
get_config_dir() {
    local tool="$1"
    echo "${XDG_CONFIG_HOME:-$HOME/.config}/$tool"
}

# Get data directory (XDG compliant)
get_data_dir() {
    local tool="$1"
    echo "${XDG_DATA_HOME:-$HOME/.local/share}/$tool"
}

# Export functions
export -f log_info log_success log_warning log_error log_step
export -f command_exists package_installed ensure_package
export -f safe_symlink merge_config ensure_dir confirm
export -f detect_shell get_config_dir get_data_dir
